export const PROVIDER_ADD = 'PROVIDER_ADD';
export const PROVIDER_UPDATE = 'PROVIDER_UPDATE';
export const PROVIDER_DELETE = 'PROVIDER_DELETE';
export const PROVIDER_STATUS = 'PROVIDER_STATUS';
export const PRODUCT_ADD = 'PRODUCT_ADD';
export const PRODUCT_DELETE = 'PRODUCT_DELETE';
export const PRODUCT_DELETE_PROVIDER = 'PRODUCT_DELETE_PROVIDER';
export const PRODUCT_UPDATE = 'PRODUCT_UPDATE';